[general]
ENABLE_BLOCKCHAIN = "False"
ENABLE_ARDUINO = "False"
USE_GOERLI = "True"
USE_MAINNET = "False"
USE_GOERLI_ADDRESS = "0x0B60EE161d7b67fa231e9565dAFF65b34553bC6F"  
USE_MAINNET_ADDRESS = "0x4073E38f71b2612580E9e381031B0c38B3B4C27E"
USE_METADATA_ADDRESS = "0x580fdc17a820e3c0d17fbcd1137483c5332fceb6"
GOERLI_FAILSAFE=1
MAINNET_FAILSAFE=0
max_rounds=0

[audio]
device_bias=-100
threshold_bias=0